services:
  mongodb:
    image: mongo:8.0
    container_name: udsm_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-udsm_db}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
